const KEY='optishield.settings';
const DEFAULT_SETTINGS={enabled:true,mode:'canvas2d',intensity:50,jitter:40,edgeInstability:38,ocrDisruption:34,frequencyDisruption:32,adaptiveTemporalPhaseShifting:true,subpixelChromaDrift:true,edgeReconstructionPoisoning:true,compressionInterferencePatterns:true,debugPanel:false,reducedMotion:false,lowEyeStrain:true,dyslexiaFriendly:false,highContrastCompatible:true,disabledSites:[]};
const DEFAULT_STATS={fps:60,frameMs:16.7,droppedFrames:0,recommendedMode:'canvas2d',renderer:'canvas2d',qualityScale:1,perturbationStrength:50,ocrResistance:54};
async function getSettings(){const r=await chrome.storage.local.get(KEY);return {...DEFAULT_SETTINGS,...(r[KEY]||{})};}
async function setSettings(patch){const next={...(await getSettings()),...patch};await chrome.storage.local.set({[KEY]:next});return next;}
function sendSettings(settings){chrome.runtime.sendMessage({type:'OPTISHIELD_SETTINGS_UPDATED',settings}).catch(()=>{});}
function slider(label,key,value,help=''){return `<label class="control"><span class="control-row"><span>${label}</span><strong id="v-${key}">${value}%</strong></span><input data-key="${key}" type="range" min="0" max="100" value="${value}">${help?`<small>${help}</small>`:''}</label>`;}
function check(label,key,checked){return `<label class="check"><input data-key="${key}" type="checkbox" ${checked?'checked':''}> ${label}</label>`;}
let settings=DEFAULT_SETTINGS;
function render(){document.getElementById('controls').innerHTML=`${slider('Overall intensity','intensity',settings.intensity)}${slider('Subpixel jitter','jitter',settings.jitter)}${slider('Edge instability','edgeInstability',settings.edgeInstability)}${slider('OCR disruption','ocrDisruption',settings.ocrDisruption)}${slider('Frequency disruption','frequencyDisruption',settings.frequencyDisruption)}${check('Adaptive temporal phase shifting','adaptiveTemporalPhaseShifting',settings.adaptiveTemporalPhaseShifting)}${check('Subpixel chroma drift','subpixelChromaDrift',settings.subpixelChromaDrift)}${check('Edge reconstruction poisoning','edgeReconstructionPoisoning',settings.edgeReconstructionPoisoning)}${check('Compression interference patterns','compressionInterferencePatterns',settings.compressionInterferencePatterns)}${check('Local developer diagnostics panel','debugPanel',settings.debugPanel)}`;document.getElementById('disabledSites').value=settings.disabledSites.join('\n');}
document.addEventListener('input',async e=>{const el=e.target;if(el.id==='disabledSites'){settings=await setSettings({disabledSites:el.value.split('\n').map(v=>v.trim().toLowerCase()).filter(Boolean)});sendSettings(settings);return;}if(!el.dataset?.key)return;const key=el.dataset.key;settings=await setSettings({[key]:el.type==='checkbox'?el.checked:Number(el.value)});sendSettings(settings);if(el.type==='range')document.getElementById(`v-${key}`).textContent=el.value+'%';});
(async()=>{settings=await getSettings();render();})();
